### ISSUE TITLE
Fix Unit tests

### ISSUE THREAD

**Issue by whereismyroot** [ita-social-projects/WhatBackend#12]
Unit tests are testing controllers now with mocked services. Basically, they do nothing. Refactor unit tests to test service methods.

**Comment by sober607** [comment]
Tests allocations:
Maxim - StudentController
Sergey- MentorConsoller
Bogan - ThemeConsoller, AccountConsoller
Eugene - StudentConsoller
Anastia - StudentGroupsConsoller
Vlad - LessonConsoller
