### ISSUE TITLE
Add services for Calendar page to AdminPanel

### ISSUE THREAD

**Issue by andy-dendy-repo** [ita-social-projects/WhatBackend#444]
AP Client should be able to obtain filtered scheduled events (POST /api/schedules/events)

**Comment by gingerbread-monster** [comment]
We need to add corresponding services so the Calendar page (that should be implemented in https://github.com/ita-social-projects/WhatBackend/issues/445) can obtain all required data.

Services to implement inside AdminPanel:
1. `ScheduleService`
2. `CalendarService` (should form the required ViewModel for Calendar page)
