### ISSUE TITLE
Fluent validation issue

### ISSUE THREAD

**Issue by Serwlashev** [ita-social-projects/WhatBackend#497]
In case of an error, the services return an error code. But this is not a flexible and comfortable decision. It was decided to replace it with fluent validation. Create your own issue, specific to each service in the project and change the old error codes with fluent validation (example you can find in EventService).  Fluent validation should check only the main problems. For example, id cannot be null and should be more than zero. The fluent validator shouldn't make any calls to the database - if an entity doesn't exist the repository should just throw NotFoundException and then ExceptionHandleMiddleware must catch it. Also, add unit tests to your pull request to check if you didn't break some important validation logic.

**Comment by DemetriosKoras** [comment]
Already done in https://github.com/ita-social-projects/WhatBackend/pull/507, https://github.com/ita-social-projects/WhatBackend/pull/519, https://github.com/ita-social-projects/WhatBackend/pull/528, https://github.com/ita-social-projects/WhatBackend/pull/529, https://github.com/ita-social-projects/WhatBackend/pull/530, https://github.com/ita-social-projects/WhatBackend/pull/532, https://github.com/ita-social-projects/WhatBackend/pull/535.
