### ISSUE TITLE
[POST Add schedule] 'Schedule can be created with startDate bigger than finishDate"

### ISSUE THREAD

**Issue by orfate** [ita-social-projects/WhatBackend#555]
**Reproducible:** always.

**Preconditions**
1. Swagger with project must be opened (https://whatbackend.azurewebsites.net/index.html);
2. User must be authorized as Admin with valid bearer token.

**Steps to reproduce**
1. Go to 'Schedules' component
2. Open POST request with  '/api/schedules' endpoint
3. Set startDate bigger than finishDate
4. Execute request

![image](https://user-images.githubusercontent.com/37227089/126493041-0b64e0c3-c769-4c68-99bc-f6f44a4c609b.png)

**Actual result**
![image](https://user-images.githubusercontent.com/37227089/126493129-6167baf4-a57d-48bb-91fa-91360add831e.png)

**Expected result**
![image](https://user-images.githubusercontent.com/37227089/126493165-668e3e20-220f-43d0-a703-6273e879839e.png)

**Comment by elizabeth-grant-20** [comment]
Everything works correctly on the development/dp-192-04 branch.
