### ISSUE TITLE
[POST Addition of new student]  Wrong output status code

### ISSUE THREAD

**Issue by ArsenVlasov** [ita-social-projects/WhatBackend#564]
**Environment**: Windows 10 (x64), Google Chrome v.91.0.4472.164
**Reproducible**: always

**Preconditions**
1. Swagger with project must be opened (https://whatbackend.azurewebsites.net/index.html);
2. User must be authorized as Admin with valid bearer token.

**Steps to reproduce**
1. Go to 'Account' component.
2. Open GET request with '/api/accounts/NotAssigned' endpoint.
3. Get id of random active user without role.
![chrome_84NQ9F5aTw](https://user-images.githubusercontent.com/65674878/126770894-a84bda5e-0b0b-45b8-a45d-26ae9e73ff92.png)
4. Go to 'Students' component.
5. Open POST request with '/api/students/{accountId}' endpoint.
6. Fill field with id from step#2.

**Actual result**:
![chrome_zhZqnmYcCo](https://user-images.githubusercontent.com/65674878/126771150-5526f0d2-9ff5-4852-8c96-e6f943a083ea.png)

500 Status code

**Expected result**:
200 Status code

**Comment by elizabeth-grant-20** [comment]
Everything works correctly on the development/dp-192-04 branch.
