### ISSUE TITLE
NullReferenceException given when trying to click on Homeworks in Panel (logged in as Secretary)

### ISSUE THREAD

**Issue by elizabeth-grant-20** [ita-social-projects/WhatBackend#744]
Run Api and then run Panel, log in as a secretary (for example, with these credentials: 
**email**: john.williams@example.com
**password**: r_Z4DPD4) and go to 'Homeworks' tab. The exception you will get:

![image](https://user-images.githubusercontent.com/85963700/141283079-84355466-b426-4866-a355-f9052c29c3a6.png)

**Comment by leshikevich** [comment]
https://github.com/ita-social-projects/WhatBackend/pull/770
