### ISSUE TITLE
Check if all endpoints are listed on the wiki

### ISSUE THREAD

**Issue by AccorDDD** [ita-social-projects/WhatBackend#773]
You need to check if all the endpoints are listed in the wiki and if they are missing, then you will need to add
1) Pull all changes from the dev branch
2) Launch our API (Swagger)
3) Also open the wiki ( https://github.com/ita-social-projects/WhatBackend/wiki/Endpoint-accessibility )

And then you start looking at Swagger and compare endpoints with the wiki
For Example: 
![image](https://user-images.githubusercontent.com/59435854/148989953-fc2569ed-f0b3-488f-9934-83da58bb998d.png)
![image](https://user-images.githubusercontent.com/59435854/148989985-2d8f8fb6-c21d-4ca0-b8e0-27f78f5cce34.png)

It happens that some endpoints are simply not listed in the wiki and you need to add them

For example:
![image](https://user-images.githubusercontent.com/59435854/148990239-403f0a64-c126-46af-adc9-c4e0af7985f5.png)
![image](https://user-images.githubusercontent.com/59435854/148990320-59dc2226-0780-4ad4-8835-f3d7b180c25d.png)

To change the information on the site, at the very top right you will find the Edit button

![image](https://user-images.githubusercontent.com/59435854/148990604-35780bb6-a673-46cf-8600-12cebd9fa2d6.png)

To find information about which roles have access to the endpoint, you must open the controllers folder in the API

Suppose you have an endpoint that is bound to the controller of the Stunedt Group, open the controller and look at the attributes to the method
There you will see the Authorize attribute and in it the roles that this endpoint is available to

If there is no such attribute, then the endpoint is available to all roles.

![image](https://user-images.githubusercontent.com/59435854/148991348-81c4dcf3-e7db-40fd-a0fd-a26a73fac6cc.png)

**Comment by DmitryTkachenko** [comment]
Was corrected the Wiki relatively  the endpoints.
