### ISSUE TITLE
Fix logic in Marks and Visits

### ISSUE THREAD

**Issue by Soctarian** [ita-social-projects/WhatBackend#808]
Visit can not handle field marks, marks should handl one instead. Also in Marks  db tab, field "Type" should be changed, instead of 0 - HomeWork, 1 - Visits it is better to delete Visits type and add more types, like control work, test, session, sprint mark, etc. The main issue is to split Marks and Visits tabs among themselves, add StudentID, LessonID, StudentMatk tabs from Marks.

![marks_tab](https://user-images.githubusercontent.com/43894436/155318831-7955d2c4-604c-4050-8f4d-3a30900f194a.png)

![visits_tab](https://user-images.githubusercontent.com/43894436/155318855-46b60cd5-c6bd-4a78-b780-99bd85863607.png)

**Comment by BohdanZaliubovskyi** [comment]
Actual issue:
https://github.com/ita-social-projects/WhatBackend/issues/902
