### ISSUE TITLE
API_'Schedules'_Schedule is added after sending POST request to add new schedule with invalid 'daysOfWeek' value

### ISSUE THREAD

**Issue by VolodymyrKhabarov** [ita-social-projects/WhatBackend#821]
**Environment:** Windows 10
**Reproducible:** always
**Build found:** last commit from

**Description:** Schedule is added after sending POST request to add new schedule with invalid 'daysOfWeek' value. There should be '400' status code with 'Can not create schedule due to wrong request data' error.

**Steps to reproduce:**

1. Make POST request to REST endpoint https://whatbackend.azurewebsites.net/api/v2/schedules with wrong 'daysOfWeek' data, other values are valid. Request body contains JSON object:

{
"pattern":
{ "type": 1, "interval": 1, "daysOfWeek": [ 7 ] },
"range":
{ "startDate": "2022-04-03T10:00:00.000Z", "finishDate": "2022-04-10T10:00:00.000Z" },
"context":
{ "groupID": 1, "themeID": 1, "mentorID": 1 }
}

**Actual result:**

Status code 200. Response body: {{{ "id": 173, "studentGroupId": 1, "eventStart": "2022-04-03T10:00:00Z", "eventFinish": "2022-04-10T10:00:00Z", "pattern": 1, "events": [ { "id": 39077, "eventOccuranceId": 173, "studentGroupId": 1, "themeId": 1, "mentorId": 1, "lessonId": null, "eventStart": "2022-04-10T10:00:00Z", "eventFinish": "2022-04-10T10:00:00" } ], "storage": 35184372088960 }}}

**Expected result:**

Status code: 400. Error: Can not create schedule due to wrong request data.

**Labels to be added:**
Priority ('Medium'), Severity ('Minor').

https://user-images.githubusercontent.com/97453653/160796463-d4bb3f0b-9fcd-48e9-8a36-3ade3ee8b4ff.mp4

**Comment by Ssashaa** [comment]
New validators have been added. The bug is closed.
