### ISSUE TITLE
API_'Schedules'_Filter does not find all events by the time specified in 'StartDate' parameter after sending POST request

### ISSUE THREAD

**Issue by FrankyMarch** [ita-social-projects/WhatBackend#831]
**Environment:** Windows 10 Pro (x64), Google Chrome Version: 98.0.4758.102 
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/WhatBackend

**Pre-conditions:**
@User:  Administrator or Secretary
1. @User  is logged  in the system:  https://whatbackend.azurewebsites.net/index.html?urls.primaryName=WHAT%20Project%20API%20v2
2. At least 1 schedule (with 2 events) is created in the system:
(Template of Responce Body)
{
  "id": ...,
  "studentGroupId": ...,
  "eventStart": "YYYY-MM-DDTT10:00:00",
  "eventFinish": "YYYY-MM-DDTT10:00:00",
  "pattern": ...,
  "events": [
    {
      "id": ...,
      "eventOccuranceId": ...,
      "studentGroupId": ...,
      "themeId": ...,
      "mentorId": ...,
      "lessonId": null,
      "eventStart": "YYYY-MM-DDTT10:00:00",
      "eventFinish": "YYYY-MM-DDTT10:00:00"
    },
{
      "id": ...,
      "eventOccuranceId": ...,
      "studentGroupId": ...,
      "themeId": ...,
      "mentorId": ...,
      "lessonId": null,
      "eventStart": "YYYY-MM-DDTT10:00:00",
      "eventFinish": "YYYY-MM-DDTT10:00:00"
    }
  ],
  "storage": ...
}

**Steps to reproduce:**
1. Make POST request to REST endpoint:  https://whatbackend.azurewebsites.net/index.html?urls.primaryName=WHAT%20Project%20API%20v2/api/v2/schedules/events with startDate of created Schedule from pre-conditions in textarea:
{
  "eventOccurrenceID": ...,
  "startDate": "yyyy-mm-ddT00:00:00"
}

**Actual result:**
1. Status Code 200 OK)
2. Responce body contains all events matching specified Schedule, becides first event: 
[
{
      "id": ...,
      "eventOccuranceId": ...,
      "studentGroupId": ...,
      "themeId": ...,
      "mentorId": ...,
      "lessonId": null,
      "eventStart": "YYYY-MM-DDTT10:00:00",
      "eventFinish": "YYYY-MM-DDTT10:00:00"
    }
  ]

**Expected result:**
1. Status Code 200 OK)
2. Responce body contains all events matching specified Schedule:
[
{
      "id": ...,
      "eventOccuranceId": ...,
      "studentGroupId": ...,
      "themeId": ...,
      "mentorId": ...,
      "lessonId": null,
      "eventStart": "YYYY-MM-DDTT10:00:00",
      "eventFinish": "YYYY-MM-DDTT10:00:00"
    },
{
      "id": ...,
      "eventOccuranceId": ...,
      "studentGroupId": ...,
      "themeId": ...,
      "mentorId": ...,
      "lessonId": null,
      "eventStart": "YYYY-MM-DDTT10:00:00",
      "eventFinish": "YYYY-MM-DDTT10:00:00"
    }
  ]

**Note:**
... - valid ID
"startDate": "YYYY-MM-DDThh:mm:ss" - valid value of "startDate"
The user gets all events matching to specific time and date, if  the filtering specifies time one minute less

**User story and test case links:**
User story: https://jira.softserve.academy/browse/DW-15
Test case: https://jira.softserve.academy/browse/DW-388

**Labels to be added:**
'Bug', Priority ('Medium'), Severity ('Major'), Type ('Functional')

**Comment by da-real-ivanpan** [comment]
Bug is not reproducable: sending endpoint request returns every fitting entry from database.
