### ISSUE TITLE
API_'Export'_Status Code 500 appears after sending POST request unauthorized user instead of Status Code 401

### ISSUE THREAD

**Issue by iratequilla** [ita-social-projects/WhatBackend#838]
****Environment**:** Windows 10 Pro (x64), Google Chrome Version: 100.0.4896.60
**Reproducible:** always
**Build found:** last commit from https://github.com/ita-social-projects/WhatBackend 

**Pre-conditions:**
@user:  unauthorized
3 students are created in system
file with extension  XLSX is created in system 

**Steps to reproduce:**

Make POST request to EXPORT endpoint:  https://whatbackend.azurewebsites.net/api/v2/exports/studentResults/ with valid student ID and file extension 

**Actual result:**

Status Code 500 (Error: Internal Server Error)
Body response content:
{
"StatusCode": 500,
"Message": {"StatusCode":500,"Message":"Internal Server Error. Not authorized!"}

**Expected result:**

Status Code 401 (Error: Unauthorized)
Body response content:
{
"error": {
"code": 1,
"message": "Unauthorized"
}
}

**User story and test case links:**
User story: https://jira.softserve.academy/browse/DW-222
Test case: https://jira.softserve.academy/browse/DW-411

**Labels to be added:**
'Bug', Priority ('High'), Severity ('Critical'), Type ('Functional')
![Screenshot_36](https://user-images.githubusercontent.com/97450285/161524400-2d9398de-b3f4-490d-8aac-2d3ea7b010e1.jpg)

**Comment by BobTheSuperman** [comment]
**Can't reproduce.**

![image](https://user-images.githubusercontent.com/40039501/163729842-a79b9acc-9e5a-4375-85c3-412680cca82a.png)
![unauthorize_export_response](https://user-images.githubusercontent.com/40039501/163729851-af45dd37-35f1-4d67-bb98-fa4605e7c2d1.png)
