### ISSUE TITLE
Add ability to edit secretary (WHAT Panel) 

### ISSUE THREAD

**Issue by Ssashaa** [ita-social-projects/WhatBackend#853]
We have an edit secretary button, but it doesn't work. Add the ability to edit according to the example of other pages (Student, Mentors)

![image](https://user-images.githubusercontent.com/86352018/164715074-f5f4e5b3-7011-4b08-98d8-2b79a3457e9c.png)

**Comment by BohdanZaliubovskyi** [comment]
I take this issue.
